# Generated by Copilot on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='degree_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]