# Generated by Django 6.0.5 on 2026-05-28 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('ecommerce', 'E-Commerce'), ('media', 'Media'), ('consulting', 'Consulting'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=50)),
                ('size', models.CharField(blank=True, choices=[('1-10', '1–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('201-500', '201–500'), ('500+', '500+')], max_length=10)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On Site')], default='on_site', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('stipend_min', models.PositiveIntegerField(blank=True, null=True)),
                ('stipend_max', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='jobs', to='students.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
